server:
  port: 8183

domain:
  payment:
    name: payment

spring:
  application:
    name: awesome-payment-service
  datasource:
    url: jdbc:mysql://localhost:3309/awesome
    username: root
    password: awesome-mariadb
    platform: mysql
    initialization-mode: always
#    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: labs
                password: awesome-rabbitmq
      bindings:
        orderCreated:
          destination: orderExchange
          group: payment.orderCreated
          content-type: application/json
        orderCanceled:
          destination: orderExchange
          group: payment.orderCanceled
          content-type: application/json
        PaymentOutput:
          destination: paymentExchange
          content-type: application/json
      rabbit:
        bindings:
          orderCreated:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: order.OrderCreated.#
          orderCanceled:
              consumer:
                autoBindDlq: true
              bindingRoutingKey: order.OrderCanceled.#
          PaymentOutput:
            producer:
              routing-key-expression: headers['routeTo']
              
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"